/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.shoppingsans.gui;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Matthew
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        new Thread(){
            public void run(){
                while(true){
                    Calendar cal = new GregorianCalendar();
                    
                    /* Set AM PM to text */
                    String am_pm_text;
                    if(cal.get(Calendar.AM_PM) == 0){
                        am_pm_text = "AM";
                    }else{
                        am_pm_text = "PM";
                    }
                    
                    /* Parse to text */
                    String hour_string = String.format("%02d", cal.get(Calendar.HOUR));
                    String minute_string = String.format("%02d", cal.get(Calendar.MINUTE));
                    String second_string = String.format("%02d", cal.get(Calendar.SECOND));
                    
                    String time_text = hour_string + ":" + minute_string + ":" + second_string + " " + am_pm_text;                    
                    clock.setText(time_text);
                    
                    
                    
                    /* Set Tanggal */
                    String day;
                    switch (cal.get(Calendar.DAY_OF_WEEK)) {
                        case Calendar.SUNDAY: day = "Sunday"; break;
                        case Calendar.MONDAY: day = "Monday"; break;
                        case Calendar.TUESDAY: day = "Tuesday"; break;
                        case Calendar.WEDNESDAY: day = "Wednesday"; break;
                        case Calendar.THURSDAY: day = "Thursday"; break;
                        case Calendar.FRIDAY: day = "Friday"; break;
                        case Calendar.SATURDAY: day = "Saturday"; break;
                        default: day = ""; break;
                    }
                    
                    String tgl;
                    Integer __tanggal = cal.get(Calendar.DATE);
                    tgl = __tanggal.toString();
                    
                    String month;
                    switch(cal.get(Calendar.MONTH)){
                        case Calendar.JANUARY : month = "January"; break;
                        case Calendar.FEBRUARY : month = "February"; break;
                        case Calendar.MARCH : month = "March"; break;
                        case Calendar.APRIL : month = "April"; break;
                        case Calendar.MAY : month = "May"; break;
                        case Calendar.JUNE : month = "June"; break;
                        case Calendar.JULY : month = "July"; break;
                        case Calendar.AUGUST : month = "August"; break;
                        case Calendar.SEPTEMBER : month = "September"; break;
                        case Calendar.OCTOBER : month = "October"; break;
                        case Calendar.NOVEMBER : month = "November"; break;
                        case Calendar.DECEMBER : month = "December"; break;
                        default : month = ""; break;
                    }
                    
                    String year;
                    Integer __year = cal.get(Calendar.YEAR);
                    year = __year.toString();
                    
                    tanggal.setText(day + ", " + tgl + " " + month + " " + year);
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 43, 74));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 198, 111));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME TO SHOPPING SANS");

        tanggal.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal.setText("DAY, TGL BULAN TAHUN");

        clock.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("HH:MM:SS AM");
        clock.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bintang H.J.                                                   Henry A.S.R.                                                   Matthew M.                                                   Azmi H.Z.                                                   A.Nadil          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(clock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clock)
                .addContainerGap(510, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
