/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.shoppingsans.gui;
import com.shoppingsans.Datastore.DataStore;
import com.shoppingsans.Plugins.JarClassLoader;

import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import java.io.IOException;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.FileDialog;
import java.awt.Frame;
import javax.xml.bind.JAXBException;
import javax.xml.crypto.Data;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.io.FilenameFilter;
import java.lang.reflect.*;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;


/**
 *
 * @author ahmad
 */
public class Settings extends javax.swing.JPanel {
    JarClassLoader jcl;
    public static boolean show = false;
    /**
     * Creates new form Settings
     */
    DataStore ds = new DataStore();
    public Settings() throws JAXBException, IOException, ClassNotFoundException {
        initComponents();
        ds = new DataStore();
        
        switch (ds.getConfig().getSaveas()) {
            case "xml":
                jComboBox2.setSelectedIndex(1);
                break;
            case "json":
                jComboBox2.setSelectedIndex(0);
                break;
            case "obj":
                jComboBox2.setSelectedIndex(2);
                break;
            default:
                jComboBox2.setSelectedIndex(3);
                break;
        }
        
        /* Fill in the ComboBox */
        jComboBox3.removeAll();
        for(int i = 0; i < ds.getConfig().getPlugins().getPath().size(); i++){
            File f = new File(ds.getConfig().getPlugins().getPath().get(i));
            String name = f.getName().substring(0, f.getName().lastIndexOf("."));
            jComboBox3.addItem(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        UploadPluginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SimpanService = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        MataUangField = new javax.swing.JComboBox<>();

        // HIDE DIS
        ServiceLabel = new javax.swing.JLabel();
        DiskonLabel = new javax.swing.JLabel();
        TextLabel = new javax.swing.JLabel();
        KursButton1 = new javax.swing.JButton();
        SimpanTax = new javax.swing.JButton();
        SimpanDiskon = new javax.swing.JButton();
        ServiceField = new javax.swing.JTextField();
        DiskonField = new javax.swing.JTextField();
        TaxField = new javax.swing.JTextField();

        ServiceLabel.setVisible(false);
        DiskonLabel.setVisible(false);
        TextLabel.setVisible(false);
        SimpanTax.setVisible(false);
        SimpanDiskon.setVisible(false);
        ServiceField.setVisible(false);
        DiskonField.setVisible(false);
        TaxField.setVisible(false);
        SimpanService.setVisible(false);

        MataUangField.addItem("IDR");
         /* Search through if there exists */        
        for(int i = 0; i < ds.getConfig().getPlugins().getPath().size(); i++){
            try {
                JarClassLoader jcl = new JarClassLoader(ds.getConfig().getPlugins().getPath().get(i));
                File f = new File(ds.getConfig().getPlugins().getPath().get(i));
                String name = f.getName().substring(0, f.getName().lastIndexOf("."));
                Class<?> c = jcl.getClassLoader().loadClass(name);
                Set <String> keys = ds.getConfig().getMapKurs().keySet();
                MataUangField.removeAllItems();
                for(String key: keys){
                    MataUangField.addItem(key);
                }
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (ds.getConfig().getShow() || show){
            magic();
        }

        setBackground(new java.awt.Color(45, 43, 74));
        setPreferredSize(new java.awt.Dimension(1268, 685));

        jLabel1.setBackground(new java.awt.Color(45, 43, 74));
        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 198, 111));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Settings");

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipe Data Penyimpanan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML", "OBJ", "SQL" }));

        UploadPluginButton.setBackground(new java.awt.Color(242, 198, 111));
        UploadPluginButton.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        UploadPluginButton.setText("Upload Plugin");
        UploadPluginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPluginButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pilih Plugin Untuk Dihapus");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(242, 198, 111));
        jButton2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(242, 198, 111));
        jButton3.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(242, 198, 111));
        jButton4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jButton4.setText("Change Path");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        SimpanService.setBackground(new java.awt.Color(242, 198, 111));
        SimpanService.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        SimpanService.setText("Simpan");
        SimpanService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanServiceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mata Uang");

        MataUangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MataUangFieldActionPerformed(evt);
            }
        });

        ServiceLabel.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        ServiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServiceLabel.setText("Service Charge");

        DiskonLabel.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        DiskonLabel.setForeground(new java.awt.Color(255, 255, 255));
        DiskonLabel.setText("Diskon");

        TextLabel.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        TextLabel.setForeground(new java.awt.Color(255, 255, 255));
        TextLabel.setText("Tax");

        KursButton1.setBackground(new java.awt.Color(242, 198, 111));
        KursButton1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        KursButton1.setText("Simpan");
        KursButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KursButton1ActionPerformed(evt);
            }
        });

        SimpanTax.setBackground(new java.awt.Color(242, 198, 111));
        SimpanTax.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        SimpanTax.setText("Simpan");
        SimpanTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanTaxActionPerformed(evt);
            }
        });

        SimpanDiskon.setBackground(new java.awt.Color(242, 198, 111));
        SimpanDiskon.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        SimpanDiskon.setText("Simpan");
        SimpanDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDiskonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(KursButton1)
                                                .addGap(62, 62, 62))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(SimpanDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(DiskonField))
                                                .addGap(63, 63, 63)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(56, 56, 56)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(TaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(SimpanTax))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(MataUangField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(ServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(SimpanService, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(DiskonLabel)
                                .addGap(164, 164, 164)
                                .addComponent(TextLabel)
                                .addGap(154, 154, 154)
                                .addComponent(ServiceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UploadPluginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 385, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MataUangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KursButton1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiskonLabel)
                    .addComponent(TextLabel)
                    .addComponent(ServiceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiskonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SimpanTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SimpanDiskon))
                .addGap(18, 18, 18)
                .addComponent(UploadPluginButton)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UploadPluginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // create a file dialog for opening .jar files
        FileDialog dialog = new FileDialog((Frame) null, "Open JAR file", FileDialog.LOAD);
        dialog.setFilenameFilter((dir, name) -> name.toLowerCase().endsWith(".jar"));
    
        // show the dialog and wait for the user to select a file
        dialog.setVisible(true);
    
        // get the selected file and create a JarClassLoader
        String filename = dialog.getFile();
        if (filename != null) {
            try {
                String path = dialog.getDirectory() + filename;
                System.out.println("You chose to open this file: " + path);
                ds.getConfig().getPlugins().getPath().add(path);
                ds.saveAs();
                jcl = new JarClassLoader(path);
                String name = filename.substring(0, filename.lastIndexOf("."));
                Main frame = (Main)SwingUtilities.getAncestorOfClass(Main.class, this);
                try{
                    Component obj = jcl.loadClassObject(name);
                    frame.addTab(obj);
                }
                catch(Exception e){
                    Class<?> c = jcl.getClassLoader().loadClass(name);
                    Set <String> keys = ds.getConfig().getMapKurs().keySet();
                    MataUangField.removeAllItems();
                    for(String key : keys){
                        MataUangField.addItem(key);
                    }
                    String temp = "ModifyPrice";
                    if(name.equals(temp)){
                        System.out.println("Masuk");
                        ds.getConfig().setShow(true);
                        ds.saveAs();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String temp = (String) jComboBox2.getSelectedItem();
            temp = temp.toLowerCase();
            ds.getConfig().setSaveas(temp);
            ds.saveAs();
        } catch (JAXBException | IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jComboBox3.getSelectedItem() != null){
            for(int i = 0; i < ds.getConfig().getPlugins().getPath().size(); i++){
                if(ds.getConfig().getPlugins().getPath().get(i).contains((String)jComboBox3.getSelectedItem())){
                    try {
                        if (ds.getConfig().getPlugins().getPath().get(i).contains("Kurs")){
                            MataUangField.removeAllItems();
                            MataUangField.addItem("IDR");
                            ds.getConfig().getMapKurs().clear();
                            ds.getConfig().getMapKurs().put("IDR", 1);
                            ds.getConfig().setCurrentKurs("IDR");
                        }
                        if(ds.getConfig().getPlugins().getPath().get(i).contains("ModifyPrice")){
                            ds.getConfig().setShow(false);
                            ds.getConfig().setDiskon(0);
                            ds.getConfig().setService(0);
                            ds.getConfig().setTax(0);
                        }
                        ds.getConfig().getPlugins().getPath().remove(i);
                        jComboBox3.removeItemAt(i);
                        ds.saveAs();
                        JOptionPane.showMessageDialog(this, "Plugin berhasil dihapus, silakan restart program agar perubahan dapat dilakukan!", "Delete Success", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    } catch (JAXBException ex) {
                        Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    System.out.println("WEH");
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        // Show the file chooser dialog
        int result = fileChooser.showOpenDialog(this);

        // Check if the user clicked the "Open" button
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                // Get the selected file path
                String path = fileChooser.getSelectedFile().getAbsolutePath()+"\\";
                
                // Display the selected file path in a message dialog
                JOptionPane.showMessageDialog(this, "Selected folder: " + path);
                
                ds.getConfig().setPath(path);
                ds.saveAs();
            } catch (JAXBException | FileNotFoundException ex) {
                Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void SimpanServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanServiceActionPerformed
        int service = Integer.parseInt(ServiceField.getText());
        if (service > 100){
            service = 100;
        } else if (service < 0){
            service = 0;
        }
        ds.getConfig().setService(service);
        try {
            ds.saveAs();
        } catch (FileNotFoundException | JAXBException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SimpanServiceActionPerformed

    private void MataUangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MataUangFieldActionPerformed
    
    }//GEN-LAST:event_MataUangFieldActionPerformed

    private void KursButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KursButton1ActionPerformed
        ds.getConfig().setCurrentKurs((String) MataUangField.getSelectedItem());
        try {
            ds.saveAs();
        } catch (FileNotFoundException | JAXBException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_KursButton1ActionPerformed

    private void SimpanTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanTaxActionPerformed
        int tax = Integer.parseInt(TaxField.getText());
        if (tax > 100){
            tax = 100;
        } else if (tax < 0){
            tax = 0;
        }
        ds.getConfig().setTax(tax);
        try {
            ds.saveAs();
        } catch (FileNotFoundException | JAXBException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SimpanTaxActionPerformed

    private void SimpanDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDiskonActionPerformed
        int diskon = Integer.parseInt(DiskonField.getText());
        if (diskon > 100){
            diskon = 100;
        } else if (diskon < 0){
            diskon = 0;
        }
        ds.getConfig().setDiskon(diskon);
        try {
            ds.saveAs();
        } catch (FileNotFoundException | JAXBException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_SimpanDiskonActionPerformed

    public static void magic(){
        ServiceLabel.setVisible(true);
        DiskonLabel.setVisible(true);
        TextLabel.setVisible(true);
        SimpanTax.setVisible(true);
        SimpanDiskon.setVisible(true);
        ServiceField.setVisible(true);
        DiskonField.setVisible(true);
        TaxField.setVisible(true);
        SimpanService.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField DiskonField;
    private static javax.swing.JLabel DiskonLabel;
    private static javax.swing.JButton KursButton1;
    private javax.swing.JComboBox<String> MataUangField;
    private static javax.swing.JTextField ServiceField;
    private static javax.swing.JLabel ServiceLabel;
    private static javax.swing.JButton SimpanDiskon;
    private static javax.swing.JButton SimpanService;
    private static javax.swing.JButton SimpanTax;
    private static javax.swing.JTextField TaxField;
    private static javax.swing.JLabel TextLabel;
    private javax.swing.JButton UploadPluginButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
